/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author LENOVO
 */
public class Bahasa_ENG extends javax.swing.JFrame {

    /**
     * Creates new form Bahasa
     */
    public Bahasa_ENG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCari = new javax.swing.JButton();
        btIDN = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btIndo = new javax.swing.JButton();
        btDaftarKata = new javax.swing.JButton();
        btInformasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCari.setContentAreaFilled(false);
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });
        getContentPane().add(btCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, 40));

        btIDN.setContentAreaFilled(false);
        btIDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIDNActionPerformed(evt);
            }
        });
        getContentPane().add(btIDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 100, 40));

        btExit.setContentAreaFilled(false);
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        getContentPane().add(btExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 70, 40));

        btIndo.setContentAreaFilled(false);
        btIndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIndoActionPerformed(evt);
            }
        });
        getContentPane().add(btIndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 170, 180));

        btDaftarKata.setContentAreaFilled(false);
        btDaftarKata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDaftarKataActionPerformed(evt);
            }
        });
        getContentPane().add(btDaftarKata, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 110, 40));

        btInformasi.setContentAreaFilled(false);
        btInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformasiActionPerformed(evt);
            }
        });
        getContentPane().add(btInformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bahasa ENG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIDNActionPerformed
        // TODO add your handling code here:
        new DaftarKata_ENG().setVisible(true);
        dispose();
    }//GEN-LAST:event_btIDNActionPerformed

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        // TODO add your handling code here:
        new menuCari_ENG().setVisible(true);
        dispose();
    }//GEN-LAST:event_btCariActionPerformed

    private void btDaftarKataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDaftarKataActionPerformed
        // TODO add your handling code here:
        new DaftarKata_ENG().setVisible(true);
        dispose();
    }//GEN-LAST:event_btDaftarKataActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformasiActionPerformed
        // TODO add your handling code here:
        new Informasi_ENG().setVisible(true);
        dispose();
    }//GEN-LAST:event_btInformasiActionPerformed

    private void btIndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIndoActionPerformed
        // TODO add your handling code here:
        new Bahasa().setVisible(true);
        dispose();
    }//GEN-LAST:event_btIndoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bahasa_ENG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bahasa_ENG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bahasa_ENG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bahasa_ENG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bahasa_ENG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCari;
    private javax.swing.JButton btDaftarKata;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btIDN;
    private javax.swing.JButton btIndo;
    private javax.swing.JButton btInformasi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
